// angular-sample/src/app/list/edit.component.ts

import { Component } from '@angular/core';
import {StoreService} from '../store';
import { Routes, RouterModule, Router, ActivatedRoute } from '@angular/router';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import * as MyValidators from '../validators';

@Component({
  selector: 'app-list-edit',
  templateUrl: './edit.component.html',
})
export class ListEditComponent {

    form: FormGroup;
    id: string;

    constructor(private store: StoreService, private route: ActivatedRoute, private router: Router) {
        const comboBoxValues = store.comboBoxValues;
        this.route.params.subscribe(params => {
            console.log(params);
            if (params['id']) {
              const v = comboBoxValues.filter(c => c.value===params['id']);
              if (v.length === 1) {
                  this.id = v[0].value;
                this.form = new FormGroup({
                    label: new FormControl(v[0].label, [Validators.required, Validators.minLength(1), Validators.maxLength(5)]),
                    value: new FormControl({ value: v[0].value, disabled: true }),
                    minValue: new FormControl(v[0].minValue.toFixed(),
                        [Validators.required, MyValidators.isNumeric(), Validators.min(10), Validators.max(1000)]),
                    maxValue: new FormControl(v[0].maxValue.toFixed(),
                        [Validators.required, MyValidators.isNumeric(), Validators.min(10), Validators.max(1000)]),
                    step: new FormControl(v[0].step.toFixed(),
                    [Validators.required, MyValidators.isNumeric(), Validators.min(5), Validators.max(100)]),
                }, [MyValidators.minLessThanMax])
              }
            }
          });
    }

    back() {
        this.router.navigate(['/list', this.id, 'view']);
    }

    save() {
        this.store.updateItem(this.id, this.form.value);
        this.router.navigate(['/list', this.id, 'view']);
    }
}
<div >
        <div>
                <h5 class="card-title">
                    <a [routerLink]="['/list',value,'view']"><i class="text-dark fa fa-arrow-circle-left"></i></a> View item
                </h5>
        
                <form [formGroup]="form">
                    <div class="form-group">
                        <label for="name">Value:</label>
                        <input type="text" class="form-control" formControlName="value"/>
                    </div>                        
                    <div class="form-group">
                        <label for="name">Label:</label>
                        <input type="text" [ngClass]="{'is-invalid' : form.get('label').invalid}" class='form-control' formControlName="label" placeholder="Enter label"/>
                        <div *ngIf="form.get('label').errors && form.get('label').errors.required" class="invalid-feedback">Must not be empty</div>
                        <div *ngIf="form.get('label').errors && form.get('label').errors.minlength" class="invalid-feedback">Must be at least 1 character</div>
                        <div *ngIf="form.get('label').errors && form.get('label').errors.maxlength" class="invalid-feedback">Must be at most 5 characters</div>
                    </div>                        
                    <div class="form-group">
                        <label for="name">Minimum Value:</label>
                        <input type="text" [ngClass]="{'is-invalid' : form.get('minValue').invalid}" class='form-control' formControlName="minValue" placeholder="Enter min value"/>
                        <div *ngIf="form.get('minValue').errors && form.get('minValue').errors.required" class="invalid-feedback">Must not be empty</div>
                        <div *ngIf="form.get('minValue').errors && form.get('minValue').errors.isNumeric" class="invalid-feedback">Must be a number</div>
                        <div *ngIf="form.get('minValue').errors && form.get('minValue').errors.min" class="invalid-feedback">Must be at least 10</div>
                        <div *ngIf="form.get('minValue').errors && form.get('minValue').errors.max" class="invalid-feedback">Must be at most 1000</div>
                        <div *ngIf="form.get('minValue').errors && form.get('minValue').errors.max" class="invalid-feedback">Must be at most 1000</div>
                        <div *ngIf="form.errors?.minLessThanMax" class="invalid-feedback">Must be less than the maxmimum</div>
                    </div>                        
                    <div class="form-group">
                        <label for="name">Maximum Value:</label>
                        <input type="text" [ngClass]="{'is-invalid' : form.get('maxValue').invalid}" class='form-control' formControlName="maxValue" placeholder="Enter max value"/>
                        <div *ngIf="form.get('maxValue').errors && form.get('maxValue').errors.required" class="invalid-feedback">Must not be empty</div>
                        <div *ngIf="form.get('maxValue').errors && form.get('maxValue').errors.isNumeric" class="invalid-feedback">Must be a number</div>
                        <div *ngIf="form.get('maxValue').errors && form.get('maxValue').errors.min" class="invalid-feedback">Must be at least 10</div>
                        <div *ngIf="form.get('maxValue').errors && form.get('maxValue').errors.max" class="invalid-feedback">Must be at most 1000</div>
                        <div *ngIf="form.errors?.minLessThanMax" class="invalid-feedback">Must be more than the minimum</div>
                    </div>                        
                    <div class="form-group">
                        <label for="name">Step:</label>
                        <input type="text" [ngClass]="{'is-invalid' : form.get('step').invalid}" class='form-control' formControlName="step" placeholder="Enter step"/>
                        <div *ngIf="form.get('step').errors && form.get('step').errors.required" class="invalid-feedback">Must not be empty</div>
                        <div *ngIf="form.get('step').errors && form.get('step').errors.isNumeric" class="invalid-feedback">Must be a number</div>
                        <div *ngIf="form.get('step').errors && form.get('step').errors.min" class="invalid-feedback">Must be at least 5</div>
                        <div *ngIf="form.get('step').errors && form.get('step').errors.max" class="invalid-feedback">Must be at most 100</div>
                    </div>        
                    {{this.form.errors | json}}                
                    <div class="mt-2">
                        <button type="button" href="#" class="btn btn-primary" [disabled]="form.invalid" (click)="save()">Save</button>
                        <button type="button" href="#" class="ml-3 btn btn-secondary" (click)="back()">Cancel</button>
                    </div>     
                </form>
            </div>
</div>

// vue-sample/src/views/list/EditComponent.vue
<template>
    <div>
        <h5 class="card-title">
            <router-link :to="{ name: 'list.view', params: { value: value }}"><i class="text-dark fa fa-arrow-circle-left"></i></router-link> View item
        <!--
        <div class="ml-auto" style="float: right"><a href="#" @click.prevent="save"><i class="fa fa-check-circle"></i></a></div>
        -->
        </h5>

        <form>
            <div class="form-group">
                <label for="name">Value:</label>
                <input type="text" class="form-control" :value="value" name="name" disabled="disabled"/>
            </div>                        
            <div class="form-group">
                <label for="name">Label:</label>
                <input type="text" :class="{'is-invalid' : $v.label.$error, 'form-control': true}" v-model.lazy.trim="$v.label.$model" name="name" placeholder="Enter label"/>
                <div v-if="$v.label.$error" class="invalid-feedback">{{errorsLabel}}</div>
            </div>                        
            <div class="form-group">
                <label for="name">Minimum Value:</label>
                <input type="text" :class="{'is-invalid' : $v.minValue.$error, 'form-control': true}" v-model.lazy.trim="$v.minValue.$model" name="name" placeholder="Enter min value"/>
                <div v-if="$v.minValue.$error" class="invalid-feedback">{{errorsMinValue}}</div>
            </div>                        
            <div class="form-group">
                <label for="name">Maximum Value:</label>
                <input type="text" :class="{'is-invalid' : $v.maxValue.$error, 'form-control': true}" v-model.lazy.trim="$v.maxValue.$model" name="name" placeholder="Enter max value"/>
                <div v-if="$v.maxValue.$error" class="invalid-feedback">{{errorsMaxValue}}</div>
            </div>                        
            <div class="form-group">
                <label for="name">Step:</label>
                <input type="text" :class="{'is-invalid' : $v.step.$error, 'form-control': true}" v-model.lazy.trim="$v.step.$model" name="name" placeholder="Enter step"/>
                <div v-if="$v.step.$error" class="invalid-feedback">{{errorsStep}}</div>
            </div>                        
            <div class="mt-2">
                <button type="button" href="#" class="btn btn-primary" @click="save" :disabled="$v.$invalid">Save</button>
                <button type="button" href="#" class="ml-3 btn btn-secondary" @click="back">Cancel</button>
            </div>

        </form>
    </div>
</template>

<script>
import Vue from "vue";
import { required, minLength, minValue, maxValue, maxLength, numeric } from 'vuelidate/lib/validators'

let  smallerThanMax = function(value) {
    if (!value) return true;
    if (this.$v.maxValue.$error) return true;
    return Number(value) < Number(this.maxValue);
};
let buildErrorMessages = function(v, messages) {
    let r = [];
    for (let key in messages) {
        if (!v[key]) return messages[key];
    }
    return r;
}

export default Vue.extend({
  name: "list",
  created() {
    console.log("created");
    if (!this.valid) {
        this.$router.push({name: 'list'});
    }
  },
  data() {
    console.log("data");
    let value = this.$store.getters.getComboBoxValue(this.$route.params.value);
    if (!value) {
        return {
            label: '',
            value: '',
            minValue: '',
            maxValue: '',
            step: '',    
            valid: false
        };
    }
    return {...value, valid: true, dirty: false};
  },
  methods: {
      back() {
          console.log("BACK");
          this.$router.push({name: 'list.view', params: {value: this.value}});
      },
      save() {
          console.log("SAVE");
          this.$store.dispatch("updateListItem", {
              label: this.label,
              value: this.value,
              minValue: Number(this.minValue),
              maxValue: Number(this.maxValue),
              step: Number(this.step),
          });
          this.$store.dispatch('pushFlashMessage', 'update was successful');
          this.$router.push({name: 'list.view', params: {value: this.value,}});
      }
  },
  computed: {
      errorsLabel() {
          return buildErrorMessages(this.$v.label, {
              required: 'Must not be empty',
              minLength: 'Must be at least 1 character',
              maxLength: 'Must be at most 5 characters',
          });
      },
      errorsValue() {
          return buildErrorMessages(this.$v.value, {
              required: 'Must not be empty',
              minLength: 'Must be at least 1 character',
              maxLength: 'Must be at most 5 characters',
          });
      },
      errorsMinValue() {
          return buildErrorMessages(this.$v.minValue, {
            required: 'Must not be empty',
            numeric: 'Must be a number',
            minValue:  'Must be at least 10',
            maxValue:  'Must be at most 1000',
            smallerThanMax: 'Must be less than the maximum value',
          });
      },
      errorsMaxValue() {
          return buildErrorMessages(this.$v.maxValue, {
            required: 'Must not be empty',
            numeric: 'Must be a number',
            minValue:  'Must be at least 10',
            maxValue:  'Must be at most 1000',
          }).concat(
            this.$v.minValue.numeric && !this.$v.minValue.smallerThanMax ?
                 'Must be bigger than the minimum value' : []
          );
      },
      errorsStep() {
          return buildErrorMessages(this.$v.step, {
            required: 'Must not be empty',
            numeric: 'Must be a number',
            minValue:  'Must be at least 5',
            maxValue:  'Must be at most 100',
          })
      },
  },
  components: {},
  validations: {
    label: {
        required,
        minLength: minLength(1),
        maxLength: maxLength(5),
    },
    value: {
        required,
        minLength: minLength(1),
        maxLength: maxLength(5),
    },
    minValue: {
        required,
        numeric,
        minValue: minValue(10),
        maxValue: maxValue(1000),
        smallerThanMax,

    },
    maxValue: {
        required,
        numeric,
        minValue: minValue(10),
        maxValue: maxValue(1000),
    },
    step: {
        required,
        numeric,
        minValue: minValue(5),
        maxValue: maxValue(100),
    },
  }
});
</script>
