// angular-sample/src/app/list/list.component.ts

import { Component } from '@angular/core';
import { IProfileData, IComboBoxValue, ISelectionData } from '../types';
import {StoreService} from '../store';

@Component({
  selector: 'app-list-list',
  templateUrl: './list.component.html',
})
export class ListListComponent {
    comboBoxValues: IComboBoxValue[];

    constructor(store: StoreService) {
        this.comboBoxValues = store.comboBoxValues;
    }
}
<div>
    <h5 class="card-title">Search list of combobox entries</h5>
    <div class="list-group">
        <a [routerLink]="[item.value, 'view']" class="list-group-item list-group-item-action flex-column align-items-start" 
            *ngFor="let item of comboBoxValues; let i=index">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ item.label }}</h5>
                <small>{{ i+1 }}</small>
            </div>
            <small class="text-muted">Label: {{item.label}}, value: {{item.value}}, minValue: {{item.minValue}}, maxValue: {{item.maxValue}}, step: {{item.step}}</small>
        </a>    
    </div>
</div>

// vue-sample/src/views/list/ListComponent.vue
<template>
    <div>
        <h5 class="card-title">Search list of combobox entries</h5>
        <div class="list-group">
            <router-link :to="{ name: 'list.view', params: { value: item.value }}" class="list-group-item list-group-item-action flex-column align-items-start" v-for="(item, index) in comboBoxValues" :key="item.value">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ item.label }}</h5>
                    <small>{{ index+1 }}</small>
                </div>
                <small class="text-muted">Label: {{item.label}}, value: {{item.value}}, minValue: {{item.minValue}}, maxValue: {{item.maxValue}}, step: {{item.step}}</small>
            </router-link>    
        </div>
    </div>
</template>

<script>
import Vue from "vue";
import { mapState } from 'vuex';

export default Vue.extend({
  name: "list",
  computed: {
      ...mapState(['comboBoxValues'])
  }

});
</script>
