// angular-sample/src/app/list/detail.component.ts

import { Component } from '@angular/core';
import { IProfileData, IComboBoxValue, ISelectionData } from '../types';
import {StoreService} from '../store';
import { Routes, RouterModule, Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-list-detail',
  templateUrl: './detail.component.html',
})
export class ListDetailComponent {

    label: string;
    value: string;
    minValue: string;
    maxValue: string;
    step: string;

    constructor(store: StoreService, private route: ActivatedRoute) {
        const comboBoxValues = store.comboBoxValues;
        this.route.params.subscribe(params => {
            console.log(params);
            if (params['id']) {
              let v = comboBoxValues.filter(c => c.value===params['id']);
              if (v.length === 1) {
                this.label = v[0].label;
                this.value = v[0].value;
                this.minValue = v[0].minValue.toFixed();
                this.maxValue = v[0].maxValue.toFixed();
                this.step = v[0].step.toFixed();
              }
            }
          });
    }
}
<div>
    <h5 class="card-title"><a [routerLink]="['/list']"><i class="text-dark fa fa-arrow-circle-left"></i></a> View item
    <div class="ml-auto" style="float: right"><a [routerLink]="['/list',value,'edit']"><i class="text-dark fa fa-edit"></i></a></div>
    </h5>

    <div *ngIf="message" class="alert alert-success" role="alert">
        {{message}}
    </div>

    <div>
        <div class="form-group">
            <label for="name">Label:</label>{{label}}
        </div>                        
        <div class="form-group">
            <label for="name">Value:</label>
            {{value}}
        </div>                        
        <div class="form-group">
            <label for="name">Minimum Value:</label>
            {{minValue}}
        </div>                        
        <div class="form-group">
            <label for="name">Maximum Value:</label>
            {{maxValue}}
        </div>                        
        <div class="form-group">
            <label for="name">Step:</label>
            {{step}}
        </div>                        
    </div>
</div>

// react-my-form/src/list/DetailComponent.tsx
import * as React from 'react';
import FlashMessage from '../FlashMessage';
import { Link } from 'react-router-dom';
import { connect } from 'react-redux';
import { IComboBoxValue, IState } from '../types';
import {RouteComponentProps} from "react-router";

let edit = (evt: React.SyntheticEvent) => {
    console.log("edit");
};
let back = (evt: React.SyntheticEvent) => {
    console.log("back");
};

interface IProps {
    comboBoxValue:IComboBoxValue;
    message: string
};

const DetailComponent = (props: IProps) => {
    let {comboBoxValue, message} = props;
    let {label, value, minValue, maxValue, step} = comboBoxValue;
    return (<div>
        <h5 className="card-title"><Link to='/list'><i className="text-dark fa fa-arrow-circle-left"/></Link> View item
            <div className="ml-auto" style={{float: 'right'}}><Link to={`/list/${value}/edit`}><i className="text-dark fa fa-edit"/></Link></div>
        </h5>

        <FlashMessage/>

        <form>
            <div className="form-group">
                <label htmlFor="name">Label:</label>{label}
            </div>
            <div className="form-group">
                <label htmlFor="name">Value:</label>
                {value}
            </div>
            <div className="form-group">
                <label htmlFor="name">Minimum Value:</label>
                {minValue}
            </div>
            <div className="form-group">
                <label htmlFor="name">Maximum Value:</label>
                {maxValue}
            </div>
            <div className="form-group">
                <label htmlFor="name">Step:</label>
                {step}
            </div>
        </form>
    </div>)
};


const mapStateToProps = (state: IState, props: RouteComponentProps<{value:string}>) : IProps => {
    console.log("Detail Component mapStateToProps", state, props);
    let filtered = state.comboBoxValues.filter(c => c.value === props.match.params.value);
    if (filtered.length !== 1) { props.history.replace('/list') };
    return {
        comboBoxValue: filtered[0],
        message: state.flashMessage,
    }
}

const ConnectedDetailComponent = connect(mapStateToProps)(DetailComponent);
export default ConnectedDetailComponent;
