// vue-sample/src/App.vue
<template>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <router-link class="navbar-brand" tag="a" active-class="active" :to="{name:'home'}">Vue.js Sample</router-link>
            <ul class="navbar-nav mr-auto">
                <router-link class="nav-item" tag="li" active-class="active" to='/profile'><a class="nav-link">Profile</a></router-link>
                <router-link class="nav-item" tag="li" active-class="active" to='/list'><a class="nav-link">List</a></router-link>
                <router-link class="nav-item" tag="li" active-class="active" to='/complex'><a class="nav-link">Complex</a></router-link>
            </ul>
        </nav>
        <div class="container-fluid">
            <router-view/>
        </div>
    </div>
</template>

<style>
</style>

<script>
import Vue from 'vue';
import store from './store';

export default Vue.extend({
  name: 'app',
  store
});
</script>

// react-formik/src/App.tsx
import * as React from 'react';
import { BrowserRouter as Router, Route, NavLink} from "react-router-dom";
import { Provider } from 'react-redux';

import Home from './Home';
import Complex from './Complex';
import Profile from './Profile';
import ListView from './list/ListView';
import LiNavLink from './LiNavLink';

import { createStore } from 'redux'
import AppReducer from './reducers';

const store = createStore(AppReducer)

class App extends React.Component {
  public render() {
    return (
        <Provider store={store}>
            <Router>
                <div>
                    <nav className="navbar navbar-expand-lg navbar-light bg-light">
                        <NavLink activeClassName="active" className="navbar-brand" to="/" >React.js Sample</NavLink>
                        <ul className="navbar-nav mr-auto">
                            <LiNavLink to='/profile'>Profile</LiNavLink>
                            <LiNavLink to='/list'>List</LiNavLink>
                            <LiNavLink to='/complex'>Complex</LiNavLink>
                        </ul>
                    </nav>
                    <div className="container-fluid">
                        <Route exact={true} path="/" component={Home} />
                        <Route path="/list" component={ListView}/>
                        <Route path="/complex" component={Complex} />
                        <Route path="/profile" component={Profile} />
                    </div>
                </div>
            </Router>
        </Provider>
    );
  }
}



export default App;
