// vue-sample/src/views/Home.vue
<template>
    <div class="jumbotron mt-4">
        <h1 class="display-4">This is an example for vue.js</h1>
        <p class="lead">It shows a master-detail page, a simple and a complex form</p>
    </div>
</template>

<script>
import Vue from 'vue';

export default Vue.extend({
  name: 'home'
});
</script>

// react-formik/src/Home.tsx
import * as React from 'react';


const Home = () => (
    <div className="jumbotron mt-4">
        <h1 className="display-4">This is an example for react.js with redux, formik, react-router</h1>
        <p className="lead">It shows a master-detail page, a simple and a complex form</p>
    </div>
  );

export default Home;
