// vue-sample/src/views/Profile.vue
<template>
    <div class="row justify-content-center m-4">
        <div class="col-8">
            <div v-if="message" class="alert alert-success" role="alert">
                 {{message}}
            </div>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Profile</h5>
                    <form>
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" :class="{'is-invalid' : $v.profile.name.$error, 'form-control': true}" v-model.lazy.trim="$v.profile.name.$model" name="name" placeholder="Enter name" :disabled="readonly"/>
                            <div v-if="$v.profile.name.$error" class="invalid-feedback">Please enter a name with 4 to 13 characters</div>
                        </div>
                        <div class="form-group">
                            <label for="email">E-mail</label>
                            <input type="text" :class="{'is-invalid' : $v.profile.email.$error, 'form-control': true}" v-model.lazy.trim="$v.profile.email.$model" name="email" placeholder="Enter e-mail" :disabled="readonly"/>
                            <div v-if="$v.profile.email.$error" class="invalid-feedback">Please enter a valid e-mail address</div>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" v-model="$v.profile.allowPhone.$model" id="allowPhone" :disabled="readonly">
                            <label class="form-check-label" for="allowPhone">
                                Allow phone calls
                            </label>
                        </div>
                        <div class="form-group">
                            <label for="phone">Phone number</label>
                            <input type="text" :class="{'is-invalid' : $v.profile.phone.$error, 'form-control': true}" v-model.lazy.trim="$v.profile.phone.$model" name="phone" placeholder="Enter phone number" :disabled="readonly || !profile.allowPhone"/>
                            <div v-if="$v.profile.phone.$error" class="invalid-feedback">Please enter a valid phone number</div>
                        </div>
                    </form>
                    <div class="mt-2">
                        <button type="button" href="#" class="btn btn-primary" @click="save" :disabled="$v.$invalid">Save</button>
                        <button type="button" href="#" class="ml-3 btn btn-secondary" @click="cancel">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import Vue from 'vue';
import cloneDeep from 'lodash/cloneDeep';
import { required, minLength, maxLength, email } from 'vuelidate/lib/validators'

let  phoneOk = function(value) {
    console.log("phoneOk");
        if (!this.profile.allowPhone) return true;
        return minLength(3)(value) && maxLength(14)(value);
    };

export default Vue.extend({
  name: 'profile',
  data() {
        return {
            profile: cloneDeep(this.$store.state.profile),
            valid: true,
            message: '',
            readonly: false,
        };
  },
  validations: {
    profile: {
        name: {
            required,
            minLength: minLength(4),
            maxLength: maxLength(13),
        },
        email: {
            required,
            email
        },
        allowPhone: {},
        phone: {
            phoneOk: phoneOk,
        },
    },
  },
  methods: {
      cancel() {
          this.$router.push({name: 'home'});
      },
      save() {
          this.$store.commit('updateProfile', this.profile);
          this.message = 'Profile updated';
          this.readonly = true;
      },
  },
});
</script>

// react-formik/src/Profile.tsx
import * as React from 'react';
import './App.css';
import { Formik, Field, FieldArray } from 'formik';
import {alwaysTrue, required, minLength, maxLength, pattern, email, composeValidators} from './validators';
import {IProfileData} from './types'

interface IPageData {
    profile: IProfileData;
    valid: boolean;
    message: string;
    readonly: boolean;
}

let initialData : IPageData = {
    profile: {
        name: '',
        email: '',
        allowPhone: true,
        phone: '',
    },
    valid: true,
    message: '',
    readonly: false,
};

const validateName = composeValidators(required('Please enter a name'),
                                        minLength(4)('Please enter a name with min 4 characters'),
                                        maxLength(14)('Please enter a name with max 13 characters'));

const validateEMail = composeValidators(required('Please enter an e-mail'),
                                            email('Please enter a valid e-mail'));

const validatePhonenumber = composeValidators(required('Please enter a phone number'),
                                            minLength(4)('Please enter a phone number with min 4 characters'),
                                            maxLength(14)('Please enter a phone number with max 13 characters'));

const validatePhone = (allowPhone:boolean) => {console.log("validatePhone", allowPhone);
    return !allowPhone ? alwaysTrue : validatePhonenumber};


const validate = (values: IPageData) => {
    return {
        profile: {
            name  : validateName(values.profile.name),
            email :  validateEMail(values.profile.email),
            phone :  validatePhone(values.profile.allowPhone)(values.profile.phone),
        }
    };
}


const Complex = () => (
      <Formik
        initialValues={initialData}
        validateOnChange={true}
        onSubmit={(
          values,
          { setSubmitting, setErrors }
        ) => {
          console.log("submitting", values);
        }}
        validate={validate}
        render={({
          values,
          errors,
          touched,
          handleChange,
          handleBlur,
          handleSubmit,
          isSubmitting,
          setFieldValue
        }) => {
            console.log("render ", values, touched, errors);
            return (
                <div className="row justify-content-center m-4">
                        <div className="col-8">
                            {values.message && <div className="alert alert-success" role="alert">
                                {values.message}
                            </div>}
                            <div className="card">
                                <div className="card-body">
                                    <h5 className="card-title">Profile</h5>
                                    <form onSubmit={handleSubmit}>
                                        <div className="form-group">
                                            <label htmlFor="name">Name</label>
                                            <input type="text" className={(errors.profile && errors.profile.name && touched.profile && touched.profile.name? 'is-invalid' : '') + ' form-control'}
                                                value={values.profile.name} onChange={handleChange} onBlur={handleBlur}
                                                name="profile.name" placeholder="Enter name" disabled={values.readonly}/>
                                            {errors.profile && errors.profile.name && <div className="invalid-feedback">{errors.profile.name}</div>}
                                        </div>
                                        <div className="form-group">
                                            <label htmlFor="email">E-mail</label>
                                            <input type="text" className={(errors.profile && errors.profile.email && touched.profile && touched.profile.email? 'is-invalid' : '') + ' form-control'}
                                                value={values.profile.email} onChange={handleChange} onBlur={handleBlur}
                                                name="profile.email" placeholder="Enter e-mail" disabled={values.readonly}/>
                                            {errors.profile && errors.profile.email && <div className="invalid-feedback">{errors.profile.email}</div>}
                                        </div>
                                       <div className="form-check">
                                            <input className="form-check-input" name="profile.allowPhone" id="allowPhone" type="checkbox"
                                            checked={values.profile.allowPhone} onChange={handleChange} onBlur={handleBlur}
                                             disabled={values.readonly}/>
                                            <label className="form-check-label" htmlFor="allowPhone">
                                                Allow phone calls
                                            </label>
                                        </div>
                                        <div className="form-group">
                                            <label htmlFor="phone">Phone number</label>
                                            <input type="text" className={(errors.profile && errors.profile.phone && touched.profile && touched.profile.phone? 'is-invalid' : '') + ' form-control'}
                                                value={values.profile.phone} onChange={handleChange} onBlur={handleBlur}
                                                name="profile.phone" placeholder="Enter phone" disabled={values.readonly}/>
                                            {errors.profile && errors.profile.phone && <div className="invalid-feedback">{errors.profile.phone}</div>}
                                        </div>
                                    </form>
                                    <div>
                                    values: {JSON.stringify(values.profile)}
                                    </div>
                                    <div>
                                    errors: {JSON.stringify(errors)}
                                    </div>
                                    <div>
                                    touched: {JSON.stringify(touched)}
                                    </div>
                                    <div className="mt-2">
                                        <button type="button" className="btn btn-primary" disabled={!touched.profile || errors.profile ? true : false}>Save</button>
                                        <button type="button" className="ml-3 btn btn-secondary">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                )
            }}
        />
  );

  /*
 autocomplete="off"
{'is-invalid' : s.amount.$error, '
*/

export default Complex;
