// angular-sample/src/app/complex.component.ts

import { Component } from '@angular/core';
import {IColumnSelection, ISelectionData, IComboBoxValue} from './types';
import { FormControl, FormBuilder, FormArray, FormGroup, Validators } from '@angular/forms';
import * as MyValidators from './validators';
import {tap} from 'rxjs/operators';
import {StoreService} from './store';

@Component({
  selector: 'app-complex',
  templateUrl: './complex.component.html',
})
export class ComplexComponent {


    form: FormArray;
    comboBoxValues: IComboBoxValue[];

    constructor(store: StoreService) {
        this.comboBoxValues = store.comboBoxValues;
        const columns = store.columns;

        this.form = new FormArray(
            columns.map(c => new FormGroup({
                selections: new FormArray(
                    c.selections.map(this.mapSelection)
                    )
            })
        ));

        this.form.valueChanges.pipe(
        ).subscribe((val) => {
            console.log('changed form values', val);
        });
    }

    allowedSelections(columnIndex: number, selectionIndex: number) {
        // let forbidden = columns[columnIndex].selections.map(s => s.selected).filter((v,idx) => idx!=selectionIndex);
        // return this.comboBoxValues.filter(cbv => !forbidden.find(v => v===cbv.value));
        const forbidden = (this.form.controls[columnIndex].get('selections') as FormArray)
                    .controls.map(s => s.get('selected').value).filter((v,idx) => idx !== selectionIndex);
        return this.comboBoxValues.filter(cbv => !forbidden.find(v => v === cbv.value));
    }

    mapSelection(s: IColumnSelection): FormGroup {
        return new FormGroup({
                selected: new FormControl(s.selected),
                amount: new FormControl(s.amount.toFixed(), [Validators.required, MyValidators.isNumeric(), Validators.min(15), Validators.max(150)]),
                price: new FormControl(s.price ? s.price.toFixed() : '-')
        });
    }

    remove(event: any, columnIndex: number, selectionIndex: number) {
        event.preventDefault();
        (this.form.controls[columnIndex].get('selections') as FormArray).controls.splice(selectionIndex, 1);
    }

    add(event: any, columnIndex: number) {
        event.preventDefault();
        const newValue = this.allowedSelections(columnIndex, undefined)[0].value;
        const sel: IColumnSelection = {selected: newValue, amount: 15, price: undefined};
        const newControl = this.mapSelection(sel);
        (this.form.controls[columnIndex].get('selections') as FormArray).controls.push(newControl);
    }

    updatePrice (columnIdx, selectionIdx) {
        const selection: FormGroup = (this.form.controls[columnIdx].get('selections') as FormArray).controls[selectionIdx] as FormGroup;
        if (!selection.valid) {
                console.log('can\'t compute - error');
                selection.get('price').setValue('');
        } else {
          console.log('start update price')
          window.setTimeout(() => {
          console.log('finsish update price')
              const price = (Math.random() * 100 + 20).toFixed();
              selection.get('price').setValue(price);
          }, 1000);
        }
    }
}
<form [formGroup]="form" class="row justify-content-center m-4">
    <div class="col-4" *ngFor='let column of form.controls; let ci=index' [formGroupName]="ci">
        <div class="card" formGroupName='selections'>            
            <div class="card-body" *ngFor='let s of column.get("selections").controls; let si=index' [formGroupName]="si">
                <div class="row">
                    <div class="col-3">
                        <select class="form-control" (change)="updatePrice(ci,si)" formControlName="selected">
                            <option *ngFor='let opt of allowedSelections(ci, si)' [value]="opt.value">{{opt.label}}</option>
                        </select>
                    </div>
                    <div class="col-4">
                        <input type="text" autocomplete="off"  (change)="updatePrice(ci,si)" [ngClass]="{'is-invalid': s.get('amount').invalid}"  class="form-control" formControlName="amount" placeholder="Enter amount"/>
                        <div *ngIf="s.get('amount').errors && s.get('amount').errors.required" class="invalid-feedback">value missing</div>
                        <div *ngIf="s.get('amount').errors && s.get('amount').errors.isNumeric" class="invalid-feedback">must be numeric</div>
                        <div *ngIf="s.get('amount').errors && s.get('amount').errors.min" class="invalid-feedback">Must be at least 15</div>
                        <div *ngIf="s.get('amount').errors && s.get('amount').errors.max" class="invalid-feedback">Must be at most 150</div>
                    </div>
                    <div class="col-3">
                        {{s.get('price').value}} €
                    </div>
                    <div class="col-1">
                        <a href="#" (click)="remove($event, ci, si)"><i class="text-dark fa fa-trash-o"></i></a>
                    </div>
                </div>
            </div>                    
            <div class="col-1 pb-3 pt-3" *ngIf="column.get('selections').controls.length < comboBoxValues.length">
                <a href="#" (click)="add($event, ci)"><i class="text-dark fa fa-plus"></i></a>
            </div>
        </div>
    </div>
</form>

// vue-sample/src/views/Complex.vue
<template>
    <form class="row justify-content-center m-4">
        <div class="col-4" v-for="(c, c_idx) in $v.columns.$each.$iter" :key="c_idx">
            <div class="card">
                <div class="card-body" v-for="(s, s_idx) in c.selections.$each.$iter" :key="s_idx">
                    <div class="row">
                        <div class="col-3">
                            <select class="form-control" :value="s.selected.$model" @change="changeSelect(s, c_idx, s_idx, $event)">
                                <option :key="opt.value" v-for="opt in allowedSelections(comboBoxValues, c.$model.selections, s.selected.$model)" :value="opt.value">{{opt.label}}</option>
                            </select>
                        </div>
                        <div class="col-4">
                            <input type="text"  autocomplete="off" :class="{'is-invalid' : s.amount.$error, 'form-control': true}" :value="s.amount.$model" 
                                @input="inputAmount(s, c_idx, s_idx, $event)" 
                                @change="changeAmount(s, c_idx, s_idx, $event)" name="amount" placeholder="Enter amount"/>
                            <div v-if="s.amount.$error" class="invalid-feedback">{{messageFor(s.amount)}}</div>
                        </div>
                        <div class="col-3">
                            {{s.$model.price}} €
                        </div>
                        <div class="col-1">
                            <a href="#" @click="remove(c_idx, s_idx)"><i class="text-dark fa fa-trash-o"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-1 pb-3 pt-3">
                    <a href="#" @click="add(c_idx)"><i class="text-dark fa fa-plus"></i></a>
                </div>
            </div>
        </div>
    </form>                 
</template>

<script>
import Vue from 'vue';
import {allowedSelections} from '../helpers';
import { required, numeric, minValue, maxValue } from 'vuelidate/lib/validators'

export default Vue.extend({
  name: 'complex',
  data() { return {
    columns: [
        {
            selections: [
                { selected: 'B', amount: 10, price: null},
                { selected: 'D', amount: 20, price: null},
                { selected: 'E', amount: 30, price: null}
            ]
        }
        ,
        {
            selections: [{ selected: 'E', amount: 30, price: null}]
        },
        {
            selections: []
        },
    ],
  }},
  methods: {
      debug(v) { console.log("[debug] ", v);},
      changeSelect(selectModelData, c_idx, s_idx, evt) {
          selectModelData.$model.selected = evt.target.value; 
          this.updatePrice(c_idx, s_idx, selectModelData, 'selected')
      },
      changeAmount(selectModelData, c_idx, s_idx, evt) {
          console.log("evt", evt);
          selectModelData.amount.$model = evt.target.value; 
          this.updatePrice(c_idx, s_idx, selectModelData, 'selected')
      },
      inputAmount(selectModelData, c_idx, s_idx, evt) {
          console.log("evt", evt);
          selectModelData.amount.$model = evt.target.value; 
      },
      allowedSelections: allowedSelections,
      messageFor(v) {
          console.log("messageFor", v);
          if (!v.$error) return '-';
          else if (!v.required) return 'enter value';
          else if (!v.numeric) return 'must be a number';
          else if (!v.minValue) return 'must be at least 15';
          else if (!v.maxValue) return 'must be at most 150';
          return ''; 
      },
      updatePrice (columnIdx, selectionIdx, selectionModel, cause) {
          if (selectionModel.$invalid) {
              console.log("can't compute - error", cause);
                this.columns[columnIdx].selections[selectionIdx].price = '';  
          } else {
            console.log("start update price", cause)
            window.setTimeout(() => {
            console.log("finsish update price", cause)
                let price = (Math.random()*100+20).toFixed();
                this.columns[columnIdx].selections[selectionIdx].price = price;
            }, 1000);
          }
      },
      remove(columnIdx, selectionIdx) {
          this.columns[columnIdx].selections.splice(selectionIdx, 1);
      },
      add(columnIdx) {
          let newValue = allowedSelections(this.comboBoxValues, this.columns[columnIdx].selections, undefined);
          this.columns[columnIdx].selections.push({
              selected: newValue[0].value,
              amount: 10,
              price: null,
          });
      }
  },
  computed: {
    comboBoxValues() {
        return this.$store.state.comboBoxValues;
    }
  },
  validations: {
      columns: {
          $each: {
              selections: {
                $each:  {
                    selected: {
                        required
                    },
                    amount: {
                        required,
                        numeric,
                        minValue: minValue(15),
                        maxValue: maxValue(150)
                    }
                }
              }
          }
      }
  }
});
</script>
