// react-formik/src/Complex.tsx
import * as React from 'react';
import { Formik, Field, FieldArray } from 'formik';
import {required, numeric, min, max, composeValidators} from './validators';
import {ISelectionData, IColumnSelection} from './types';
import { connect } from 'react-redux';

interface IComboBoxValue {
    label: string,
    value: string,
    minValue: number,
    maxValue: number,
    step: number
}

export function allowedSelections(comboBoxValues: IComboBoxValue[], columnSelections: IColumnSelection[], selected: string|undefined) {
    console.log("allowedSelections", comboBoxValues, columnSelections, selected);
    let forbidden = columnSelections.map(s => s.selected).filter(v => v !== selected);
    return comboBoxValues.filter(cbv => !forbidden.find(v => v===cbv.value));
}

export function updatePrice(setFieldValue: (field: string, value: any) => void, selected: string, amount: string, cIdx: number, sIdx: number, errors: any) {
    console.log("updatePrice", cIdx, sIdx, selected);
    if (errors && errors.columns && errors.columns[cIdx] && errors.columns[cIdx].selections
        && errors.columns[cIdx].selections[sIdx] && errors.columns[cIdx].selections[sIdx].amount) {
        console.log("ignore updatePrice due to error");
    } else {
        console.log("updatePrice", cIdx, sIdx, selected, amount, errors) ;
        window.setTimeout(() => {
            setFieldValue(`columns[${cIdx}].selections[${sIdx}].price`, Number(amount) * 5, );
        }, 1000);
    }
}

const amountValidator = composeValidators(required('Please enter amount'), numeric('must be a number'), min(5)('Must be at least 5'), max(100)('Must be less than 100'));

class Complex extends React.Component<any> {
    public render() {
        let gComboBoxValues = this.props.comboBoxValues;
        let initialData : ISelectionData[] = this.props.complex;
        return (<div>
            <Formik
                initialValues={{
                    columns: initialData,
                }}
                validateOnChange={true}
                validate={values => {
                    let errors = {columns: values.columns.map(column => {
                        return {selections: column.selections.map(sel =>
                            ({amount: amountValidator(sel.amount as string)})
                        )}}
                    )};
                    console.log("validate errors", errors, values);
                    return errors;
                }}
                onSubmit={(
                values,
                { setSubmitting, setErrors /* setValues and other goodies */ }
                ) => {
                console.log("submitting", values);
                }}
                render={({
                values,
                errors,
                touched,
                handleChange,
                handleBlur,
                handleSubmit,
                isSubmitting,
                setFieldValue
                }) => {
                    console.log("render ", values, touched, errors);
                    return (
                    <form className="row justify-content-center m-4" onSubmit={handleSubmit}>
                        <FieldArray
                            name="columns"
                            render={colArrayHelpers => {
                                return values.columns.map((column, cIdx) =>
                                (<div className="col-4" key={cIdx}>
                                    <div className="card">
                                        <FieldArray
                                            name={`columns[${cIdx}].selections`}
                                            render={selArrayHelpers => {
                                                return values.columns[cIdx].selections.map((sel, sIdx) => (
                                                <div className="card-body" key={sIdx}>
                                                    <div className="row">
                                                        <div className="col-3">
                                                            <select name={`columns[${cIdx}].selections[${sIdx}].selected`} className="form-control" value={values.columns[cIdx].selections[sIdx].selected} onChange={(evt) => {handleChange(evt); updatePrice(setFieldValue, evt.target.value, values.columns[cIdx].selections[sIdx].amount, cIdx, sIdx, errors);}} onBlur={handleBlur}>
                                                            {
                                                                allowedSelections(gComboBoxValues, values.columns[cIdx].selections, sel.selected).map(opt =>
                                                                (
                                                                    <option key={opt.value} value={opt.value}>{opt.label}</option>
                                                                ))
                                                            }
                                                            </select>
                                                        </div>
                                                        <div className="col-4">
                                                            <input type="text"  autoComplete="off" className={errors && errors.columns && errors.columns[cIdx] &&  errors.columns[cIdx].selections && errors.columns[cIdx].selections[sIdx]
                                                                    && errors.columns[cIdx].selections[sIdx].amount ? 'is-invalid form-control' : 'form-control'}
                                                                name={`columns[${cIdx}].selections[${sIdx}].amount`}
                                                                value={values.columns[cIdx].selections[sIdx].amount} onChange={(evt) => {handleChange(evt);}} onBlur={(evt) => {handleBlur(evt); updatePrice(setFieldValue, values.columns[cIdx].selections[sIdx].selected, values.columns[cIdx].selections[sIdx].amount, cIdx, sIdx, errors);}}
                                                                placeholder="Enter amount"/>
                                                            {errors && errors.columns && errors.columns[cIdx] &&  errors.columns[cIdx].selections && errors.columns[cIdx].selections[sIdx]
                                                                    && errors.columns[cIdx].selections[sIdx].amount
                                                                && <div className="invalid-feedback">{errors.columns[cIdx].selections[sIdx].amount}</div>}
                                                        </div>
                                                        <div className="col-3">
                                                            {values.columns[cIdx].selections[sIdx].price} €
                                                        </div>
                                                        <div className="col-1">
                                                            <a href="#" onClick={(evt) => {evt.preventDefault(); selArrayHelpers.remove(sIdx)}}><i className="text-dark fa fa-trash-o"/></a>
                                                        </div>
                                                    </div>
                                                </div>
                                                ));
                                            }}
                                        />
                                        { values.columns[cIdx].selections.length < gComboBoxValues.length ?
                                        (<div className="col-1 pb-3 pt-3">
                                            <a href="#" onClick={(evt) => {evt.preventDefault(); setFieldValue('columns[${cIdx}].selections', values.columns[cIdx].selections.push({selected: allowedSelections(gComboBoxValues, values.columns[cIdx].selections, undefined)[0].value, amount: '15', price: null}));}}><i className="text-dark fa fa-plus"/></a>
                                        </div>) : null
                                        }
                                    </div>
                                </div>));
                            }}
                        />
                    </form>)
                    }}
                />
            </div>);
        }
}

  /*
 autocomplete="off"
{'is-invalid' : s.amount.$error, '
*/


const mapStateToProps = (state: any, props: any) => {
    console.log("Detail Component mapStateToProps", state, props);
    return {
        comboBoxValues: state.comboBoxValues,
        complex: state.complex,
    }
}

export default connect(mapStateToProps)(Complex);

// vue-sample/src/views/Complex.vue
<template>
    <form class="row justify-content-center m-4">
        <div class="col-4" v-for="(c, c_idx) in $v.columns.$each.$iter" :key="c_idx">
            <div class="card">
                <div class="card-body" v-for="(s, s_idx) in c.selections.$each.$iter" :key="s_idx">
                    <div class="row">
                        <div class="col-3">
                            <select class="form-control" :value="s.selected.$model" @change="changeSelect(s, c_idx, s_idx, $event)">
                                <option :key="opt.value" v-for="opt in allowedSelections(comboBoxValues, c.$model.selections, s.selected.$model)" :value="opt.value">{{opt.label}}</option>
                            </select>
                        </div>
                        <div class="col-4">
                            <input type="text"  autocomplete="off" :class="{'is-invalid' : s.amount.$error, 'form-control': true}" :value="s.amount.$model"
                                @input="inputAmount(s, c_idx, s_idx, $event)"
                                @change="changeAmount(s, c_idx, s_idx, $event)" name="amount" placeholder="Enter amount"/>
                            <div v-if="s.amount.$error" class="invalid-feedback">{{messageFor(s.amount)}}</div>
                        </div>
                        <div class="col-3">
                            {{s.$model.price}} €
                        </div>
                        <div class="col-1">
                            <a href="#" @click="remove(c_idx, s_idx)"><i class="text-dark fa fa-trash-o"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-1 pb-3 pt-3">
                    <a href="#" @click="add(c_idx)"><i class="text-dark fa fa-plus"></i></a>
                </div>
            </div>
        </div>
    </form>
</template>

<script>
import Vue from 'vue';
import {allowedSelections} from '../helpers';
import { required, numeric, minValue, maxValue } from 'vuelidate/lib/validators'

export default Vue.extend({
  name: 'complex',
  data() { return {
    columns: [
        {
            selections: [
                { selected: 'B', amount: 10, price: null},
                { selected: 'D', amount: 20, price: null},
                { selected: 'E', amount: 30, price: null}
            ]
        }
        ,
        {
            selections: [{ selected: 'E', amount: 30, price: null}]
        },
        {
            selections: []
        },
    ],
  }},
  methods: {
      debug(v) { console.log("[debug] ", v);},
      changeSelect(selectModelData, c_idx, s_idx, evt) {
          selectModelData.$model.selected = evt.target.value;
          this.updatePrice(c_idx, s_idx, selectModelData)
      },
      changeAmount(selectModelData, c_idx, s_idx, evt) {
          selectModelData.amount.$model = evt.target.value;
          this.updatePrice(c_idx, s_idx, selectModelData)
      },
      inputAmount(selectModelData, c_idx, s_idx, evt) {
          selectModelData.amount.$model = evt.target.value;
      },
      allowedSelections: allowedSelections,
      messageFor(v) {
          if (!v.$error) return '-';
          else if (!v.required) return 'enter value';
          else if (!v.numeric) return 'must be a number';
          else if (!v.minValue) return 'must be at least 15';
          else if (!v.maxValue) return 'must be at most 150';
          return '';
      },
      updatePrice (columnIdx, selectionIdx, selectionModel) {
          if (selectionModel.$invalid) {
                this.columns[columnIdx].selections[selectionIdx].price = '';
          } else {
            window.setTimeout(() => {
                let price = (Math.random()*100+20).toFixed();
                this.columns[columnIdx].selections[selectionIdx].price = price;
            }, 1000);
          }
      },
      remove(columnIdx, selectionIdx) {
          this.columns[columnIdx].selections.splice(selectionIdx, 1);
      },
      add(columnIdx) {
          let newValue = allowedSelections(this.comboBoxValues, this.columns[columnIdx].selections, undefined);
          this.columns[columnIdx].selections.push({
              selected: newValue[0].value,
              amount: 10,
              price: null,
          });
      }
  },
  computed: {
    comboBoxValues() {
        return this.$store.state.comboBoxValues;
    }
  },
  validations: {
      columns: {
          $each: {
              selections: {
                $each:  {
                    selected: {
                        required
                    },
                    amount: {
                        required,
                        numeric,
                        minValue: minValue(15),
                        maxValue: maxValue(150)
                    }
                }
              }
          }
      }
  }
});
</script>
