// angular-sample/src/app/complex.component.ts

import { Component } from '@angular/core';
import {IColumnSelection, ISelectionData, IComboBoxValue} from './types';
import { FormControl, FormBuilder, FormArray, FormGroup, Validators } from '@angular/forms';
import * as MyValidators from './validators';
import {tap} from 'rxjs/operators';
import {StoreService} from './store';

@Component({
  selector: 'app-complex',
  templateUrl: './complex.component.html',
})
export class ComplexComponent {


    form: FormArray;
    comboBoxValues: IComboBoxValue[];

    constructor(store: StoreService) {
        this.comboBoxValues = store.comboBoxValues;
        const columns = store.columns;

        this.form = new FormArray(
            columns.map(c => new FormGroup({
                selections: new FormArray(
                    c.selections.map(this.mapSelection)
                    )
            })
        ));

        this.form.valueChanges.pipe(
        ).subscribe((val) => {
            console.log('changed form values', val);
        });
    }

    allowedSelections(columnIndex: number, selectionIndex: number) {
        // let forbidden = columns[columnIndex].selections.map(s => s.selected).filter((v,idx) => idx!=selectionIndex);
        // return this.comboBoxValues.filter(cbv => !forbidden.find(v => v===cbv.value));
        const forbidden = (this.form.controls[columnIndex].get('selections') as FormArray)
                    .controls.map(s => s.get('selected').value).filter((v,idx) => idx !== selectionIndex);
        return this.comboBoxValues.filter(cbv => !forbidden.find(v => v === cbv.value));
    }

    mapSelection(s: IColumnSelection): FormGroup {
        return new FormGroup({
                selected: new FormControl(s.selected),
                amount: new FormControl(s.amount.toFixed(), [Validators.required, MyValidators.isNumeric(), Validators.min(15), Validators.max(150)]),
                price: new FormControl(s.price ? s.price.toFixed() : '-')
        });
    }

    remove(event: any, columnIndex: number, selectionIndex: number) {
        event.preventDefault();
        (this.form.controls[columnIndex].get('selections') as FormArray).controls.splice(selectionIndex, 1);
    }

    add(event: any, columnIndex: number) {
        event.preventDefault();
        const newValue = this.allowedSelections(columnIndex, undefined)[0].value;
        const sel: IColumnSelection = {selected: newValue, amount: 15, price: undefined};
        const newControl = this.mapSelection(sel);
        (this.form.controls[columnIndex].get('selections') as FormArray).controls.push(newControl);
    }

    updatePrice (columnIdx, selectionIdx) {
        const selection: FormGroup = (this.form.controls[columnIdx].get('selections') as FormArray).controls[selectionIdx] as FormGroup;
        if (!selection.valid) {
                console.log('can\'t compute - error');
                selection.get('price').setValue('');
        } else {
          console.log('start update price')
          window.setTimeout(() => {
          console.log('finsish update price')
              const price = (Math.random() * 100 + 20).toFixed();
              selection.get('price').setValue(price);
          }, 1000);
        }
    }
}
<form [formGroup]="form" class="row justify-content-center m-4">
    <div class="col-4" *ngFor='let column of form.controls; let ci=index' [formGroupName]="ci">
        <div class="card" formGroupName='selections'>            
            <div class="card-body" *ngFor='let s of column.get("selections").controls; let si=index' [formGroupName]="si">
                <div class="row">
                    <div class="col-3">
                        <select class="form-control" (change)="updatePrice(ci,si)" formControlName="selected">
                            <option *ngFor='let opt of allowedSelections(ci, si)' [value]="opt.value">{{opt.label}}</option>
                        </select>
                    </div>
                    <div class="col-4">
                        <input type="text" autocomplete="off"  (change)="updatePrice(ci,si)" [ngClass]="{'is-invalid': s.get('amount').invalid}"  class="form-control" formControlName="amount" placeholder="Enter amount"/>
                        <div *ngIf="s.get('amount').errors && s.get('amount').errors.required" class="invalid-feedback">value missing</div>
                        <div *ngIf="s.get('amount').errors && s.get('amount').errors.isNumeric" class="invalid-feedback">must be numeric</div>
                        <div *ngIf="s.get('amount').errors && s.get('amount').errors.min" class="invalid-feedback">Must be at least 15</div>
                        <div *ngIf="s.get('amount').errors && s.get('amount').errors.max" class="invalid-feedback">Must be at most 150</div>
                    </div>
                    <div class="col-3">
                        {{s.get('price').value}} €
                    </div>
                    <div class="col-1">
                        <a href="#" (click)="remove($event, ci, si)"><i class="text-dark fa fa-trash-o"></i></a>
                    </div>
                </div>
            </div>                    
            <div class="col-1 pb-3 pt-3" *ngIf="column.get('selections').controls.length < comboBoxValues.length">
                <a href="#" (click)="add($event, ci)"><i class="text-dark fa fa-plus"></i></a>
            </div>
        </div>
    </div>
</form>

// react-my-form/src/Complex.tsx
import * as React from 'react';
import {required, numeric, min, max, composeValidators, alwaysTrue} from './validators';
import {ISelectionData, IColumnSelection, IComboBoxValue} from './types';
import { connect } from 'react-redux';
import FormModel, {ComponentProps, ComponentState, TPropsForComponent} from './formModelReact';
import { FormControlMap, FormControlValue, FormControlArray } from './formModel';

export function allowedSelections(comboBoxValues: IComboBoxValue[], columnSelections: IColumnSelection[], selected: string|undefined) {
    let forbidden = columnSelections.map(s => s.selected).filter(v => v !== selected);
    return comboBoxValues.filter(cbv => !forbidden.find(v => v===cbv.value));
}

export function updatePrice(selectionModel: ReturnType<typeof forSelection>) {
    console.log("updatePrice", selectionModel);
    if (selectionModel.invalid) {
        console.log("ignore updatePrice due to error");
    } else {
        window.setTimeout(() => {
            selectionModel.children.price.value = Number(selectionModel.children.amount.value ) * 5;
        }, 1000);
    }
}

const amountValidator = composeValidators(required('Please enter amount'), numeric('must be a number'), min(5)('Must be at least 5'), max(100)('Must be less than 100'));

interface IProps {
    comboBoxValues: IComboBoxValue[];
    complex: ISelectionData[];
}

let forSelection = (selection: IColumnSelection) => {
    console.log('*forSelection', selection);
    return new FormControlMap({
    selected: new FormControlValue<string>({value: selection.selected}),
    amount: new FormControlValue<string>({value: selection.amount}),
    price: new FormControlValue<number|null>({value: null})
})};

let forSelectionsInColumn = (selections: IColumnSelection[]) => {
    console.log("*forSelectionsInColumn", selections);
    return new FormControlArray(forSelection, {values: selections});
}

let forColumn = (selectionData: ISelectionData) => {
    return new FormControlMap({
        selections: forSelectionsInColumn(selectionData.selections)
    })
}


const SingleSelection = ({selection, propsForComponent, comboBoxValues, remove, selectionsInColumn} :
    {selection: ReturnType<typeof forSelection>,
        propsForComponent: TPropsForComponent,
        comboBoxValues: IComboBoxValue[],
        remove: (evt: React.SyntheticEvent) =>void,
        selectionsInColumn: IColumnSelection[]
    }) => (
        <div className="card-body">
            <div className="row">
            <div className="col-3">
                <select className="form-control" {...propsForComponent(selection.children.selected)}
                    onChange={(evt) => {propsForComponent(selection.children.selected).onChange(evt); updatePrice(selection);}}
                    onBlur={(evt) => propsForComponent(selection.children.selected).onBlur(evt)}
                    value={propsForComponent(selection.children.selected).value}
                >
                {
                    allowedSelections(comboBoxValues, selectionsInColumn, selection.children.selected.value).map(opt =>
                    (
                        <option key={opt.value} value={opt.value}>{opt.label}</option>
                    ))
                }
                </select>
            </div>
            <div className="col-4">
                <input type="text"  autoComplete="off" className={selection.children.amount.invalid ? 'is-invalid form-control' : 'form-control'}
                    {...propsForComponent(selection.children.amount)}
                    onBlur={(evt) => {propsForComponent(selection.children.amount).onBlur(evt); updatePrice(selection);}}
                    placeholder="Enter amount"/>
                {selection.children.amount.invalid && <div className="invalid-feedback">{selection.children.amount.message}</div>}
            </div>
            <div className="col-3">
                {selection.children.price.value} €
            </div>
            <div className="col-1">
                <a href="#" onClick={remove}><i className="text-dark fa fa-trash-o"/></a>
            </div>
        </div>
    </div>)

const Column = ({formModel, propsForComponent, comboBoxValues} :
    {formModel: ReturnType<typeof forColumn>,
        propsForComponent: TPropsForComponent,
        comboBoxValues: IComboBoxValue[],
    }) => (<div className="col-4">
            <div className="card">
            {formModel.children.selections.children.map((formControlMap, idx) => {
                return <SingleSelection key={idx}
                        comboBoxValues={comboBoxValues}
                        propsForComponent = {propsForComponent}
                        selectionsInColumn = {formModel.children.selections.value}
                        remove = {(evt) => {evt.preventDefault(); formModel.children.selections.remove(idx)}}
                        selection = {formControlMap}
                    />
            }
            )}
            { formModel.children.selections.children.length < comboBoxValues.length ?
                (<div className="col-1 pb-3 pt-3">
                    <a href="#" onClick={(evt) =>
                        {   evt.preventDefault();
                            formModel.children.selections.add(
                           {selected: allowedSelections(comboBoxValues, formModel.children.selections.value, undefined)[0].value,
                            amount: '15',
                            price: null})}
                    }><i className="text-dark fa fa-plus"/></a>
                </div>) : null
            }
        </div>
    </div>);

function createFormModel(complex: ISelectionData[]) {
    return new FormControlArray((sel:ISelectionData) => forColumn(sel),
        {values: complex}
    );
}

class Complex extends React.Component<IProps, {}> {
    private formModel : ReturnType<typeof createFormModel>;

    constructor(props: IProps) {
        super(props);
        this.formModel = createFormModel(this.props.complex);
    }

    render() {
        let comboBoxValues = this.props.comboBoxValues;
        let formModel = this.formModel;

        return (<div>
            <FormModel
                formModel = { formModel }
                render = { (props) => {
                    {/*console.log("render form ", props);*/}
                    return (<div className="row justify-content-center m-4">
                        {props.formModel.children.map((col, idx) => (
                        <Column
                            formModel = {col}
                            comboBoxValues = {comboBoxValues}
                            propsForComponent = {props.propsForComponent}
                            key={idx}/>
                        ))}
                    </div>
                )}}
            />
            </div>);
    }
}

const mapStateToProps = (state: any, props: any) => {
    console.log("Detail Component mapStateToProps", state, props);
    return {
        comboBoxValues: state.comboBoxValues,
        complex: state.complex,
    }
}

export default connect(mapStateToProps)(Complex);
