// vue-sample/src/views/Home.vue
<template>
    <div class="jumbotron mt-4">
        <h1 class="display-4">This is an example for vue.js</h1>
        <p class="lead">It shows a master-detail page, a simple and a complex form</p>
    </div>
</template>

<script>
import Vue from 'vue';

export default Vue.extend({
  name: 'home'
});
</script>

// angular-sample/src/app/home.component.ts

import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
})
export class HomeComponent {
}
<div >
    <div class="jumbotron mt-4">
        <h1 class="display-4">This is an example for angular</h1>
        <p class="lead">It shows a master-detail page, a simple and a complex form</p>
    </div>

</div>
